language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "vinodh-thimmisetty-github"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
